// Mock data generator for SafeNet prototype
// This generates realistic sample data for demonstration

export const MOCK_MODERATORS = [
  {
    id: 'mod_001',
    name: 'Priya Singh',
    email: 'priya.singh@safenet.in',
    phone: '+91-98765-43210',
    language: 'hindi',
    hoursAvailable: 40,
    hourlyRate: 400,
    trainingStatus: 'verified' as const,
    trainedModules: [
      'Harassment Detection',
      'Grooming Patterns',
      'Platform Rules',
      'Hindi Abuse Lexicon',
    ],
    verifiedAt: '2026-02-15T10:30:00Z',
    joinedAt: '2026-02-01T08:00:00Z',
    totalReviews: 1250,
    accuracyScore: 94,
    currentStreak: 12,
  },
  {
    id: 'mod_002',
    name: 'Rajesh Kumar',
    email: 'rajesh.kumar@safenet.in',
    phone: '+91-87654-32109',
    language: 'hindi',
    hoursAvailable: 35,
    hourlyRate: 350,
    trainingStatus: 'verified' as const,
    trainedModules: [
      'Harassment Detection',
      'Platform Rules',
      'Hindi Abuse Lexicon',
    ],
    verifiedAt: '2026-02-20T14:00:00Z',
    joinedAt: '2026-02-05T09:15:00Z',
    totalReviews: 890,
    accuracyScore: 91,
    currentStreak: 8,
  },
  {
    id: 'mod_003',
    name: 'Anjali Sharma',
    email: 'anjali.sharma@safenet.in',
    phone: '+91-76543-21098',
    language: 'tamil',
    hoursAvailable: 40,
    hourlyRate: 420,
    trainingStatus: 'verified' as const,
    trainedModules: [
      'Harassment Detection',
      'Grooming Patterns',
      'Platform Rules',
      'Hindi Abuse Lexicon',
      'Tamil Abuse Lexicon',
    ],
    verifiedAt: '2026-02-10T11:45:00Z',
    joinedAt: '2026-01-28T07:30:00Z',
    totalReviews: 1620,
    accuracyScore: 96,
    currentStreak: 15,
  },
  {
    id: 'mod_004',
    name: 'Deepa Patel',
    email: 'deepa.patel@safenet.in',
    phone: '+91-65432-10987',
    language: 'english',
    hoursAvailable: 30,
    hourlyRate: 380,
    trainingStatus: 'in_training' as const,
    trainedModules: ['Harassment Detection', 'Platform Rules'],
    verifiedAt: undefined,
    joinedAt: '2026-03-10T10:00:00Z',
    totalReviews: 120,
    accuracyScore: 87,
    currentStreak: 2,
  },
  {
    id: 'mod_005',
    name: 'Neha Gupta',
    email: 'neha.gupta@safenet.in',
    phone: '+91-54321-09876',
    language: 'hindi',
    hoursAvailable: 40,
    hourlyRate: 410,
    trainingStatus: 'verified' as const,
    trainedModules: [
      'Harassment Detection',
      'Grooming Patterns',
      'Platform Rules',
      'Hindi Abuse Lexicon',
    ],
    verifiedAt: '2026-02-25T16:20:00Z',
    joinedAt: '2026-02-08T08:45:00Z',
    totalReviews: 980,
    accuracyScore: 93,
    currentStreak: 10,
  },
];

export const MOCK_CONTENTS = [
  {
    id: 'content_001',
    platformId: 'platform_koo',
    text: 'You are absolutely disgusting! You dont deserve to exist.',
    authorId: 'user_123',
    createdAt: '2026-03-24T09:15:00Z',
    flaggedAt: '2026-03-24T09:18:00Z',
    moderatorId: 'mod_001',
    decision: 'flagged' as const,
    severity: 'high' as const,
    category: 'harassment',
    reason: 'Death wish / life threat',
    contextUrl: 'https://koo.in/posts/12345',
  },
  {
    id: 'content_002',
    platformId: 'platform_sharechat',
    text: 'Love this video! Great content!',
    authorId: 'user_456',
    createdAt: '2026-03-24T08:45:00Z',
    flaggedAt: '2026-03-24T08:48:00Z',
    moderatorId: 'mod_002',
    decision: 'approved' as const,
    severity: 'low' as const,
    category: undefined,
    reason: undefined,
    contextUrl: 'https://sharechat.in/posts/67890',
  },
  {
    id: 'content_003',
    platformId: 'platform_koo',
    text: 'How old are you? Can we be friends? 😊',
    authorId: 'user_789',
    createdAt: '2026-03-24T07:30:00Z',
    flaggedAt: '2026-03-24T07:32:00Z',
    moderatorId: 'mod_003',
    decision: 'escalated' as const,
    severity: 'critical' as const,
    category: 'grooming',
    reason: 'Potential child grooming attempt - escalated to law enforcement',
    contextUrl: 'https://koo.in/posts/11111',
  },
  {
    id: 'content_004',
    platformId: 'platform_sharechat',
    text: 'This is a really good recipe for traditional Indian biryani!',
    authorId: 'user_234',
    createdAt: '2026-03-24T10:20:00Z',
    flaggedAt: '2026-03-24T10:22:00Z',
    moderatorId: 'mod_005',
    decision: 'approved' as const,
    severity: 'low' as const,
    category: undefined,
    reason: undefined,
    contextUrl: 'https://sharechat.in/posts/22222',
  },
  {
    id: 'content_005',
    platformId: 'platform_koo',
    text: '#[SLUR] women shouldnt be allowed on this platform!',
    authorId: 'user_567',
    createdAt: '2026-03-24T06:45:00Z',
    flaggedAt: '2026-03-24T06:47:00Z',
    moderatorId: 'mod_001',
    decision: 'flagged' as const,
    severity: 'high' as const,
    category: 'hate_speech',
    reason: 'Hate speech + gender-based discrimination',
    contextUrl: 'https://koo.in/posts/33333',
  },
  {
    id: 'content_006',
    platformId: 'platform_sharechat',
    text: 'Check out my new blog about tech tips!',
    authorId: 'user_890',
    createdAt: '2026-03-23T15:00:00Z',
    flaggedAt: '2026-03-23T15:03:00Z',
    moderatorId: 'mod_002',
    decision: 'approved' as const,
    severity: 'low' as const,
    category: undefined,
    reason: undefined,
    contextUrl: 'https://sharechat.in/posts/44444',
  },
];

// Add more pending content for the queue
export const MOCK_PENDING_CONTENTS = [
  {
    id: 'content_pending_001',
    platformId: 'platform_koo',
    text: 'Just sharing my thoughts on todays great day!',
    authorId: 'user_111',
    createdAt: '2026-03-24T11:30:00Z',
    moderatorId: undefined,
    decision: 'pending' as const,
    severity: undefined,
    category: undefined,
    contextUrl: 'https://koo.in/posts/55555',
  },
  {
    id: 'content_pending_002',
    platformId: 'platform_sharechat',
    text: 'Why are you so stupid? Delete this app!',
    authorId: 'user_222',
    createdAt: '2026-03-24T11:45:00Z',
    moderatorId: undefined,
    decision: 'pending' as const,
    severity: undefined,
    category: undefined,
    contextUrl: 'https://sharechat.in/posts/66666',
  },
  {
    id: 'content_pending_003',
    platformId: 'platform_koo',
    text: 'Are you single? Lets chat privately 😉',
    authorId: 'user_333',
    createdAt: '2026-03-24T11:50:00Z',
    moderatorId: undefined,
    decision: 'pending' as const,
    severity: undefined,
    category: undefined,
    contextUrl: 'https://koo.in/posts/77777',
  },
  {
    id: 'content_pending_004',
    platformId: 'platform_sharechat',
    text: 'Anyone want to buy crypto? Best investment!',
    authorId: 'user_444',
    createdAt: '2026-03-24T12:00:00Z',
    moderatorId: undefined,
    decision: 'pending' as const,
    severity: undefined,
    category: undefined,
    contextUrl: 'https://sharechat.in/posts/88888',
  },
  {
    id: 'content_pending_005',
    platformId: 'platform_koo',
    text: 'Beautiful sunset photo from my evening walk!',
    authorId: 'user_555',
    createdAt: '2026-03-24T12:10:00Z',
    moderatorId: undefined,
    decision: 'pending' as const,
    severity: undefined,
    category: undefined,
    contextUrl: 'https://koo.in/posts/99999',
  },
];

export const MOCK_PLATFORMS = [
  {
    id: 'platform_koo',
    name: 'Koo',
    subscriptionTier: 'enterprise' as const,
    monthlySpend: 2500000,
    activeModeratorCount: 25,
    monthlyReviewVolume: 85000,
    createdAt: '2026-01-15T10:00:00Z',
    contactEmail: 'trust@koo.in',
  },
  {
    id: 'platform_sharechat',
    name: 'ShareChat',
    subscriptionTier: 'enterprise' as const,
    monthlySpend: 3200000,
    activeModeratorCount: 35,
    monthlyReviewVolume: 120000,
    createdAt: '2026-01-20T11:00:00Z',
    contactEmail: 'safety@sharechat.com',
  },
];

export const MOCK_ALERTS = [
  {
    id: 'alert_001',
    pattern: 'New slur variant in Hindi',
    detectionCount: 45,
    region: 'north_india',
    severity: 'high' as const,
    firstDetectedAt: '2026-03-20T14:30:00Z',
    description: 'Emerging abuse term targeting women activists - detected across multiple platforms',
  },
  {
    id: 'alert_002',
    pattern: 'Coordinated harassment campaign',
    detectionCount: 120,
    region: 'south_india',
    severity: 'critical' as const,
    firstDetectedAt: '2026-03-22T09:15:00Z',
    description: 'Organized brigade targeting minority community members',
  },
  {
    id: 'alert_003',
    pattern: 'Election-related misinformation',
    detectionCount: 280,
    region: 'nationwide',
    severity: 'high' as const,
    firstDetectedAt: '2026-03-23T16:45:00Z',
    description: 'Coordinated disinformation campaign spreading false voting info',
  },
];

// Weekly analytics data for charts
export const MOCK_WEEKLY_ANALYTICS = [
  { day: 'Mon', reviews: 3200, flagged: 180, escalated: 12 },
  { day: 'Tue', reviews: 3450, flagged: 195, escalated: 14 },
  { day: 'Wed', reviews: 3100, flagged: 170, escalated: 11 },
  { day: 'Thu', reviews: 3800, flagged: 220, escalated: 18 },
  { day: 'Fri', reviews: 4200, flagged: 250, escalated: 22 },
  { day: 'Sat', reviews: 2900, flagged: 140, escalated: 8 },
  { day: 'Sun', reviews: 2100, flagged: 95, escalated: 5 },
];

// Training modules available
export const TRAINING_MODULES = [
  {
    id: 'module_harassment',
    title: 'Harassment Detection',
    description: 'Learn to identify harassment, bullying, and targeted abuse patterns',
    duration: '45 mins',
    videoUrl: '#',
  },
  {
    id: 'module_grooming',
    title: 'Grooming Patterns',
    description: 'Recognize and escalate child safety threats and grooming behaviors',
    duration: '60 mins',
    videoUrl: '#',
  },
  {
    id: 'module_platform',
    title: 'Platform Rules',
    description: 'Understand this platforms content policies and enforcement procedures',
    duration: '30 mins',
    videoUrl: '#',
  },
  {
    id: 'module_hindi',
    title: 'Hindi Abuse Lexicon',
    description: 'Master regional language abuse patterns and localized slurs',
    duration: '90 mins',
    videoUrl: '#',
  },
];
